// Unity Deterministic ISL Animation Controller & API (Prompt 77)
// Receives pre-computed ISL Animation Payload JSON generated by Python.
// Exposes Play, Pause, Repeat, Speed, Step-Through, and Debug Mode.
// ZERO translation logic contained in Unity.

using System;
using System.Collections.Generic;
using UnityEngine;
using BiISL.Avatar.Retargeting;
using BiISL.Avatar.NMM;

namespace BiISL.Avatar.Controller
{
    [Serializable]
    public class UnityISLPayloadMetadata
    {
        public string target_rig;
        public int hand_count;
        public int finger_dof_count;
        public bool has_nmm;
        public bool zero_unity_translation;
    }

    [Serializable]
    public class UnityISLPayloadDTO
    {
        public string sequence_id;
        public List<string> gloss_sequence;
        public float total_duration_sec;
        public float fps = 60.0f;
        public int total_frames;
        public List<KeyframeData> keyframes;
        public UnityISLPayloadMetadata metadata;
    }

    public class UnityISLAnimationController : MonoBehaviour
    {
        [Header("Target Retargeting & Rendering References")]
        public HumanoidRetargeter retargeter;
        public NMMController nmmController;
        public NMMDebugOverlay debugOverlay;

        [Header("Playback State (Read-Only)")]
        public bool isPlaying = false;
        public bool isRepeatEnabled = false;
        public float playbackSpeed = 1.0f;
        public int currentFrameIndex = 0;
        public bool isDebugModeEnabled = false;

        private UnityISLPayloadDTO currentPayload;
        private float frameTimer = 0.0f;

        private void Awake()
        {
            if (retargeter == null) retargeter = GetComponent<HumanoidRetargeter>();
            if (nmmController == null) nmmController = GetComponent<NMMController>();
            if (debugOverlay == null) debugOverlay = GetComponent<NMMDebugOverlay>();
        }

        public void LoadPayloadJSON(string jsonPayload)
        {
            if (string.IsNullOrEmpty(jsonPayload))
            {
                Debug.LogWarning("[UnityISLAnimationController] Empty JSON payload received.");
                return;
            }

            try
            {
                currentPayload = JsonUtility.FromJson<UnityISLPayloadDTO>(jsonPayload);
                currentFrameIndex = 0;
                isPlaying = false;
                frameTimer = 0.0f;
                Debug.Log($"[UnityISLAnimationController] Loaded payload '{currentPayload.sequence_id}' with {currentPayload.total_frames} pre-computed frames.");

                ApplyFrame(0);
            }
            catch (Exception ex)
            {
                Debug.LogError($"[UnityISLAnimationController] Failed to parse payload JSON: {ex.Message}");
            }
        }

        public void Play()
        {
            if (currentPayload != null && currentPayload.total_frames > 0)
            {
                isPlaying = true;
            }
        }

        public void Pause()
        {
            isPlaying = false;
        }

        public void SetRepeat(bool repeat)
        {
            isRepeatEnabled = repeat;
        }

        public void SetSpeed(float speedMultiplier)
        {
            if (speedMultiplier > 0.0f)
            {
                playbackSpeed = speedMultiplier;
            }
        }

        public void SeekToFrame(int frameIndex)
        {
            if (currentPayload == null || currentPayload.total_frames == 0) return;
            currentFrameIndex = Mathf.Clamp(frameIndex, 0, currentPayload.total_frames - 1);
            ApplyFrame(currentFrameIndex);
        }

        public void StepForward()
        {
            if (currentPayload == null || currentPayload.total_frames == 0) return;
            if (currentFrameIndex < currentPayload.total_frames - 1)
            {
                currentFrameIndex++;
            }
            else if (isRepeatEnabled)
            {
                currentFrameIndex = 0;
            }
            ApplyFrame(currentFrameIndex);
        }

        public void StepBackward()
        {
            if (currentPayload == null || currentPayload.total_frames == 0) return;
            if (currentFrameIndex > 0)
            {
                currentFrameIndex--;
            }
            else if (isRepeatEnabled)
            {
                currentFrameIndex = currentPayload.total_frames - 1;
            }
            ApplyFrame(currentFrameIndex);
        }

        public void SetDebugMode(bool enabled)
        {
            isDebugModeEnabled = enabled;
            if (debugOverlay != null)
            {
                debugOverlay.showOverlay = enabled;
            }
        }

        private void Update()
        {
            if (!isPlaying || currentPayload == null || currentPayload.total_frames == 0) return;

            float targetFrameDelta = (1.0f / currentPayload.fps) / playbackSpeed;
            frameTimer += Time.deltaTime;

            if (frameTimer >= targetFrameDelta)
            {
                frameTimer -= targetFrameDelta;
                StepForward();
            }
        }

        private void ApplyFrame(int index)
        {
            if (currentPayload == null || currentPayload.keyframes == null || index < 0 || index >= currentPayload.keyframes.Count) return;

            KeyframeData kf = currentPayload.keyframes[index];
            if (retargeter != null)
            {
                retargeter.ApplyKeyframe(kf);
            }
        }
    }
}
